apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6969
      nodePort: {{ .Values.service.nodePort }}
